# Generated by Django 5.2.4 on 2025-07-12 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_alter_users_managers_users_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='availability',
            field=models.JSONField(blank=True, default=list, help_text='Select multiple availability options'),
        ),
        migrations.AddField(
            model_name='users',
            name='is_banned',
            field=models.BooleanField(default=False, help_text='Indicates if the user is banned from the platform'),
        ),
        migrations.AddField(
            model_name='users',
            name='is_privete',
            field=models.BooleanField(default=False, help_text='Indicates if the user profile is private'),
        ),
    ]
