# Generated by Django 5.2.4 on 2025-07-12 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the skill', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the skill was created')),
            ],
        ),
        migrations.CreateModel(
            name='UserSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('want', 'Want'), ('offer', 'Offer')], help_text='Type of skill relationship - want or offer', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the user skill was created')),
                ('skill', models.ForeignKey(help_text='Skill that the user has', on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to='skills.skills')),
                ('user', models.ForeignKey(help_text='User who has the skill', on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'skill', 'type')},
            },
        ),
    ]
