# Generated by Django 5.2.4 on 2025-07-12 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satatus', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Status of the skill request', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the skill request was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the skill request was last updated')),
                ('offered_skill', models.ForeignKey(help_text='Skill that is being offered', on_delete=django.db.models.deletion.CASCADE, related_name='skill_offers', to='skills.skills')),
                ('receiver', models.ForeignKey(help_text='User who received the request', on_delete=django.db.models.deletion.CASCADE, related_name='skill_requests_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(help_text='User who sent the request', on_delete=django.db.models.deletion.CASCADE, related_name='skill_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('wanted_skill', models.ForeignKey(help_text='Skill that is being requested', on_delete=django.db.models.deletion.CASCADE, related_name='skill_requests', to='skills.skills')),
            ],
        ),
    ]
